["Latch Drivers"]
    regex = "Number of <CLOCK_NODE> node: (\d+)"
    default = 0

["Pi"]
    regex = "Number of <INPUT_NODE> node: (\d+)"
    default = 0

["Po"]
    regex = "Number of <OUTPUT_NODE> node: (\d+)"
    default = 0

["logic element"]
    regex = "Number of <GENERIC> node: (\d+)"
    default = 0

["latch"]
    regex = "Number of <FF_NODE> node: (\d+)"
    default = 0

#include hard_blocks.toml

