# See https://github.com/actions/labeler#common-examples for defining patterns.
# The globs use "minimatch" syntax found at https://github.com/isaacs/minimatch
#
# WARNING: Due to this file being yaml, any string starting with `*` must be
# wrapped in quotes.

# Tools
ABC:
 - abc_with_bb_support/*
 - abc_with_bb_support/**/*
 - abc/*
 - abc/**/*
ACE2:
 - ace2/*
 - ace2/**/*
blifexplorer:
 - blifexplorer/*
 - blifexplorer/**/*
Odin:
 - ODIN_II/*
 - ODIN_II/**/*
 - odin2_helper/*
 - odin2_helper/**/*
VPR:
 - vpr/*
 - vpr/**/*

# Libraries
libarchfpga:
 - libs/libarchfpga/*
 - libs/libarchfpga/**/*
libeasygl:
 - libs/libeasygl/*
 - libs/libeasygl/**/*
liblog:
 - libs/liblog/*
 - libs/liblog/**/*
libpugiutil:
 - libs/libpugiutil/*
 - libs/libpugiutil/**/*
libvtrutil:
 - libs/libvtrutil/*
 - libs/libvtrutil/**/*
external_libs:
 - libs/EXTERNAL/*
 - libs/EXTERNAL/**/*

# General areas
docs:
 - docs/*
 - docs/**/*
 - "*README*"
 - "*.md"
 - tutorial
 - "*.rst"
infra:
 - "*travis*"
 - .github/*
 - .github/**/*
 - Dockerfile
 - "*docker*"
build:
 - Makefile
 - "*.make"
 - CMakeLists.txt
 - cmake
tests:
 - "*_test.py"
 - "*test*"
 - "*TESTS*"
scripts:
 - scripts
 - "*.pl"
 - "*.py"
 - "*.sh"
VTR Flow:
 - vtr_flow

# Tag pull requests with the languages used to make it easy to see what is
# being used.
lang-hdl:
 - "*.v"
 - "*.sv"
lang-cpp:
 - "*.c*"
 - "*.h"
lang-perl:
 - "*.pl"
 - "*perl*"
lang-python:
 - "*.py"
lang-shell:
 - "*.sh"
lang-netlist:
 - "*.blif"
 - "*.eblif"
 - "*.edif"
 - "*.vqm"
lang-make:
 - "*.make"
 - Makefile
 - CMakeLists.txt
