SRC +=src/sat/cadical/cadicalSolver.c \
src/sat/cadical/cadicalTest.c \
src/sat/cadical/cadical_analyze.cpp \
src/sat/cadical/cadical_arena.cpp \
src/sat/cadical/cadical_assume.cpp \
src/sat/cadical/cadical_averages.cpp \
src/sat/cadical/cadical_backtrack.cpp \
src/sat/cadical/cadical_backward.cpp \
src/sat/cadical/cadical_bins.cpp \
src/sat/cadical/cadical_block.cpp \
src/sat/cadical/cadical_ccadical.cpp \
src/sat/cadical/cadical_checker.cpp \
src/sat/cadical/cadical_clause.cpp \
src/sat/cadical/cadical_collect.cpp \
src/sat/cadical/cadical_compact.cpp \
src/sat/cadical/cadical_condition.cpp \
src/sat/cadical/cadical_config.cpp \
src/sat/cadical/cadical_congruence.cpp \
src/sat/cadical/cadical_constrain.cpp \
src/sat/cadical/cadical_contract.cpp \
src/sat/cadical/cadical_cover.cpp \
src/sat/cadical/cadical_decide.cpp \
src/sat/cadical/cadical_decompose.cpp \
src/sat/cadical/cadical_deduplicate.cpp \
src/sat/cadical/cadical_definition.cpp \
src/sat/cadical/cadical_drattracer.cpp \
src/sat/cadical/cadical_elim.cpp \
src/sat/cadical/cadical_elimfast.cpp \
src/sat/cadical/cadical_ema.cpp \
src/sat/cadical/cadical_extend.cpp \
src/sat/cadical/cadical_external.cpp \
src/sat/cadical/cadical_external_propagate.cpp \
src/sat/cadical/cadical_factor.cpp \
src/sat/cadical/cadical_file.cpp \
src/sat/cadical/cadical_flags.cpp \
src/sat/cadical/cadical_flip.cpp \
src/sat/cadical/cadical_format.cpp \
src/sat/cadical/cadical_frattracer.cpp \
src/sat/cadical/cadical_gates.cpp \
src/sat/cadical/cadical_idruptracer.cpp \
src/sat/cadical/cadical_instantiate.cpp \
src/sat/cadical/cadical_internal.cpp \
src/sat/cadical/cadical_ipasir.cpp \
src/sat/cadical/cadical_lidruptracer.cpp \
src/sat/cadical/cadical_limit.cpp \
src/sat/cadical/cadical_logging.cpp \
src/sat/cadical/cadical_lookahead.cpp \
src/sat/cadical/cadical_lratchecker.cpp \
src/sat/cadical/cadical_lrattracer.cpp \
src/sat/cadical/cadical_lucky.cpp \
src/sat/cadical/cadical_message.cpp \
src/sat/cadical/cadical_minimize.cpp \
src/sat/cadical/cadical_occs.cpp \
src/sat/cadical/cadical_options.cpp \
src/sat/cadical/cadical_parse.cpp \
src/sat/cadical/cadical_phases.cpp \
src/sat/cadical/cadical_probe.cpp \
src/sat/cadical/cadical_profile.cpp \
src/sat/cadical/cadical_proof.cpp \
src/sat/cadical/cadical_propagate.cpp \
src/sat/cadical/cadical_queue.cpp \
src/sat/cadical/cadical_random.cpp \
src/sat/cadical/cadical_reap.cpp \
src/sat/cadical/cadical_reduce.cpp \
src/sat/cadical/cadical_rephase.cpp \
src/sat/cadical/cadical_report.cpp \
src/sat/cadical/cadical_resources.cpp \
src/sat/cadical/cadical_restart.cpp \
src/sat/cadical/cadical_restore.cpp \
src/sat/cadical/cadical_score.cpp \
src/sat/cadical/cadical_shrink.cpp \
src/sat/cadical/cadical_signal.cpp \
src/sat/cadical/cadical_solution.cpp \
src/sat/cadical/cadical_solver.cpp \
src/sat/cadical/cadical_stable.cpp \
src/sat/cadical/cadical_stats.cpp \
src/sat/cadical/cadical_subsume.cpp \
src/sat/cadical/cadical_sweep.cpp \
src/sat/cadical/cadical_terminal.cpp \
src/sat/cadical/cadical_ternary.cpp \
src/sat/cadical/cadical_tier.cpp \
src/sat/cadical/cadical_transred.cpp \
src/sat/cadical/cadical_unstable.cpp \
src/sat/cadical/cadical_util.cpp \
src/sat/cadical/cadical_var.cpp \
src/sat/cadical/cadical_veripbtracer.cpp \
src/sat/cadical/cadical_version.cpp \
src/sat/cadical/cadical_vivify.cpp \
src/sat/cadical/cadical_walk.cpp \
src/sat/cadical/cadical_watch.cpp \
src/sat/cadical/cadical_kitten.c
