SRC += src/sat/kissat/kissatSolver.c \
src/sat/kissat/kissatTest.c\
src/sat/kissat/allocate.c \
src/sat/kissat/analyze.c \
src/sat/kissat/ands.c \
src/sat/kissat/arena.c \
src/sat/kissat/assign.c \
src/sat/kissat/averages.c \
src/sat/kissat/backbone.c \
src/sat/kissat/backtrack.c \
src/sat/kissat/build.c \
src/sat/kissat/bump.c \
src/sat/kissat/check.c \
src/sat/kissat/classify.c \
src/sat/kissat/clause.c \
src/sat/kissat/collect.c \
src/sat/kissat/colors.c \
src/sat/kissat/compact.c \
src/sat/kissat/config.c \
src/sat/kissat/congruence.c \
src/sat/kissat/decide.c \
src/sat/kissat/deduce.c \
src/sat/kissat/definition.c \
src/sat/kissat/dense.c \
src/sat/kissat/dump.c \
src/sat/kissat/eliminate.c \
src/sat/kissat/equivalences.c \
src/sat/kissat/error.c \
src/sat/kissat/extend.c \
src/sat/kissat/factor.c \
src/sat/kissat/fastel.c \
src/sat/kissat/file.c \
src/sat/kissat/flags.c \
src/sat/kissat/format.c \
src/sat/kissat/forward.c \
src/sat/kissat/gates.c \
src/sat/kissat/heap.c \
src/sat/kissat/ifthenelse.c \
src/sat/kissat/import.c \
src/sat/kissat/internal.c \
src/sat/kissat/kimits.c \
src/sat/kissat/kitten.c \
src/sat/kissat/krite.c \
src/sat/kissat/learn.c \
src/sat/kissat/logging.c \
src/sat/kissat/kucky.c \
src/sat/kissat/minimize.c \
src/sat/kissat/mode.c \
src/sat/kissat/kptions.c \
src/sat/kissat/phases.c \
src/sat/kissat/preprocess.c \
src/sat/kissat/print.c \
src/sat/kissat/probe.c \
src/sat/kissat/profile.c \
src/sat/kissat/promote.c \
src/sat/kissat/proof.c \
src/sat/kissat/propbeyond.c \
src/sat/kissat/propdense.c \
src/sat/kissat/propinitially.c \
src/sat/kissat/proprobe.c \
src/sat/kissat/propsearch.c \
src/sat/kissat/queue.c \
src/sat/kissat/reduce.c \
src/sat/kissat/reluctant.c \
src/sat/kissat/reorder.c \
src/sat/kissat/rephase.c \
src/sat/kissat/report.c \
src/sat/kissat/resize.c \
src/sat/kissat/resolve.c \
src/sat/kissat/resources.c \
src/sat/kissat/restart.c \
src/sat/kissat/search.c \
src/sat/kissat/shrink.c \
src/sat/kissat/smooth.c \
src/sat/kissat/sort.c \
src/sat/kissat/stack.c \
src/sat/kissat/statistics.c \
src/sat/kissat/strengthen.c \
src/sat/kissat/substitute.c \
src/sat/kissat/sweep.c \
src/sat/kissat/terminate.c \
src/sat/kissat/tiers.c \
src/sat/kissat/trail.c \
src/sat/kissat/transitive.c \
src/sat/kissat/utilities.c \
src/sat/kissat/vector.c \
src/sat/kissat/vivify.c \
src/sat/kissat/walk.c \
src/sat/kissat/warmup.c \
src/sat/kissat/watch.c \
src/sat/kissat/weaken.c \
