SRC +=	src/base/abci/abc.c \
	src/base/abci/abcAttach.c \
	src/base/abci/abcAuto.c \
	src/base/abci/abcBalance.c \
	src/base/abci/abcBmc.c \
	src/base/abci/abcCas.c \
	src/base/abci/abcClpBdd.c \
	src/base/abci/abcClpSop.c \
	src/base/abci/abcCut.c \
	src/base/abci/abcDar.c \
	src/base/abci/abcDebug.c \
	src/base/abci/abcDress.c \
	src/base/abci/abcDsd.c \
	src/base/abci/abcEspresso.c \
	src/base/abci/abcExtract.c \
	src/base/abci/abcFpga.c \
	src/base/abci/abcFpgaFast.c \
	src/base/abci/abcFraig.c \
        src/base/abci/abcFxu.c \
        src/base/abci/abcGen.c \
        src/base/abci/abcHaig.c \
	src/base/abci/abcIf.c \
        src/base/abci/abcIvy.c \
	src/base/abci/abcLut.c \
	src/base/abci/abcMap.c \
	src/base/abci/abcMini.c \
	src/base/abci/abcMiter.c \
	src/base/abci/abcMulti.c \
	src/base/abci/abcNtbdd.c \
	src/base/abci/abcOdc.c \
	src/base/abci/abcOrder.c \
	src/base/abci/abcPart.c \
	src/base/abci/abcPlace.c \
	src/base/abci/abcPrint.c \
	src/base/abci/abcProve.c \
	src/base/abci/abcQbf.c \
	src/base/abci/abcQuant.c \
	src/base/abci/abcRec.c \
	src/base/abci/abcReconv.c \
	src/base/abci/abcRefactor.c \
	src/base/abci/abcRenode.c \
	src/base/abci/abcReorder.c \
	src/base/abci/abcRestruct.c \
	src/base/abci/abcResub.c \
	src/base/abci/abcRewrite.c \
	src/base/abci/abcRr.c \
	src/base/abci/abcSat.c \
	src/base/abci/abcStrash.c \
	src/base/abci/abcSweep.c \
	src/base/abci/abcSymm.c \
	src/base/abci/abcTiming.c \
	src/base/abci/abcUnate.c \
	src/base/abci/abcUnreach.c \
	src/base/abci/abcVerify.c \
	src/base/abci/abcXsim.c 
