all: gen_c_chain_arch_sweep.c
	g++ -g gen_c_chain_arch_sweep.c -o gen_c_chain_arch_sweep
	g++ -g gen_frac_arch_sweep.c -o gen_frac_arch_sweep

clean:
	rm -f gen_c_chain_arch_sweep
	rm -f gen_frac_arch_sweep
	rm -f *.xml

