SRC +=    src/base/abci/abc.c \
    src/base/abci/abcAttach.c \
    src/base/abci/abcAuto.c \
    src/base/abci/abcBalance.c \
    src/base/abci/abcBidec.c \
    src/base/abci/abcBm.c \
    src/base/abci/abcBmc.c \
    src/base/abci/abcCas.c \
    src/base/abci/abcCascade.c \
    src/base/abci/abcCollapse.c \
    src/base/abci/abcCut.c \
    src/base/abci/abcDar.c \
    src/base/abci/abcDebug.c \
    src/base/abci/abcDec.c \
    src/base/abci/abcDetect.c \
    src/base/abci/abcDress.c \
    src/base/abci/abcDress2.c \
    src/base/abci/abcDress3.c \
    src/base/abci/abcDsd.c \
    src/base/abci/abcEco.c \
    src/base/abci/abcExact.c \
    src/base/abci/abcExtract.c \
    src/base/abci/abcFraig.c \
    src/base/abci/abcFx.c \
    src/base/abci/abcFxu.c \
    src/base/abci/abcGen.c \
    src/base/abci/abcHaig.c \
    src/base/abci/abcIf.c \
    src/base/abci/abcIfif.c \
    src/base/abci/abcIfMux.c \
    src/base/abci/abcIvy.c \
    src/base/abci/abcLog.c \
    src/base/abci/abcLut.c \
    src/base/abci/abcLutmin.c \
    src/base/abci/abcMap.c \
    src/base/abci/abcMerge.c \
    src/base/abci/abcMfs.c \
    src/base/abci/abcMini.c \
    src/base/abci/abcMiter.c \
    src/base/abci/abcMulti.c \
    src/base/abci/abcNtbdd.c \
    src/base/abci/abcNpn.c \
    src/base/abci/abcNpnSave.c \
    src/base/abci/abcOrchestration.c \
    src/base/abci/abcOdc.c \
    src/base/abci/abcOrder.c \
    src/base/abci/abcPart.c \
    src/base/abci/abcPrint.c \
    src/base/abci/abcProve.c \
    src/base/abci/abcQbf.c \
    src/base/abci/abcQuant.c \
    src/base/abci/abcRec3.c \
    src/base/abci/abcReconv.c \
    src/base/abci/abcReach.c \
    src/base/abci/abcRefactor.c \
    src/base/abci/abcRenode.c \
    src/base/abci/abcReorder.c \
    src/base/abci/abcRestruct.c \
    src/base/abci/abcResub.c \
    src/base/abci/abcRewrite.c \
    src/base/abci/abcRpo.c \
    src/base/abci/abcRr.c \
    src/base/abci/abcRunGen.c \
    src/base/abci/abcSat.c \
    src/base/abci/abcSaucy.c \
    src/base/abci/abcScorr.c \
    src/base/abci/abcSense.c \
    src/base/abci/abcSpeedup.c \
    src/base/abci/abcStrash.c \
    src/base/abci/abcSweep.c \
    src/base/abci/abcSymm.c \
    src/base/abci/abcTim.c \
    src/base/abci/abcTiming.c \
    src/base/abci/abcUnate.c \
    src/base/abci/abcUnreach.c \
    src/base/abci/abcVerify.c \
    src/base/abci/abcXsim.c 
