#!/usr/bin/env python3
"""verify per-arch -overlay-tpldir merge for vtr_arch_rules.

uses the checked-in overlay at
  vtr_flow/misc/mosaic/min_exotic_integer_mul/rules/mult_map.v.tmpl
against an arch that has classic multiply (so mult_map.v.tmpl is loaded).
checks that the overlay marker appears in mult_map.v and that a template
not present in the overlay (add_sub_map.v.tmpl) still comes from the
shared tpldir.

requires built yosys plus mosaic plugin (mosaic.so).

usage:
  python mosaic/scripts/test_tpl_overlay.py
"""

from __future__ import print_function

import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
MOSAIC_ROOT = SCRIPT_DIR.parent
REPO_ROOT = MOSAIC_ROOT.parent

YOSYS_BIN = REPO_ROOT / "build" / "bin" / "yosys"
PLUGIN_PATH = REPO_ROOT / "build" / "share" / "yosys" / "plugins" / "mosaic.so"
SHARED_TPLDIR = REPO_ROOT / "vtr_flow" / "misc" / "mosaic" / "template" / "rules"
OVERLAY_TPLDIR = (
    REPO_ROOT / "vtr_flow" / "misc" / "mosaic" / "min_exotic_integer_mul" / "rules"
)
# k6 declares classic multiply, so mult_map.v.tmpl is actually substituted.
ARCH_XML = (
    REPO_ROOT / "vtr_flow" / "arch" / "timing" / "k6_frac_N10_frac_chain_mem32K_40nm.xml"
)
OVERLAY_MARKER = "MOSAIC_OVERLAY_MARKER min_exotic_integer_mul"


def fail(msg):
    """print a failure line and return exit code 1."""
    print("FAIL: {}".format(msg), file=sys.stderr)
    return 1


def main():  # pylint: disable=too-many-return-statements
    """run the overlay merge smoke against built yosys and mosaic.so."""
    if not YOSYS_BIN.is_file():
        return fail("yosys not found at {}".format(YOSYS_BIN))
    if not PLUGIN_PATH.is_file():
        return fail("mosaic plugin not found at {} (build vtr with WITH_MOSAIC=ON)".format(
            PLUGIN_PATH))
    overlay_mult = OVERLAY_TPLDIR / "mult_map.v.tmpl"
    if not overlay_mult.is_file():
        return fail("missing overlay template {}".format(overlay_mult))
    overlay_text = overlay_mult.read_text(encoding="utf-8")
    if OVERLAY_MARKER not in overlay_text:
        return fail("overlay template missing marker {!r}".format(OVERLAY_MARKER))
    if (OVERLAY_TPLDIR / "add_sub_map.v.tmpl").is_file():
        return fail(
            "overlay must not ship add_sub_map.v.tmpl (fallback coverage)")

    with tempfile.TemporaryDirectory(prefix="mosaic_tpl_overlay_") as tmp:
        out_dir = Path(tmp)
        script = (
            "plugin -i mosaic\n"
            "vtr_arch_rules -xml {xml} -outdir {out} "
            "-tpldir {tpl} -overlay-tpldir {overlay} "
            "-blocks multiply,adder\n"
        ).format(
            xml=ARCH_XML.as_posix(),
            out=out_dir.as_posix(),
            tpl=SHARED_TPLDIR.as_posix(),
            overlay=OVERLAY_TPLDIR.as_posix(),
        )
        proc = subprocess.run(
            [str(YOSYS_BIN), "-q", "-p", script],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            print(proc.stdout, file=sys.stderr)
            print(proc.stderr, file=sys.stderr)
            return fail("vtr_arch_rules exited {}".format(proc.returncode))

        mult_map = out_dir / "mult_map.v"
        add_sub_map = out_dir / "add_sub_map.v"
        if not mult_map.is_file():
            return fail("expected generated {}".format(mult_map))
        if not add_sub_map.is_file():
            return fail("expected generated {}".format(add_sub_map))

        mult_text = mult_map.read_text(encoding="utf-8")
        add_text = add_sub_map.read_text(encoding="utf-8")

        if OVERLAY_MARKER not in mult_text:
            return fail(
                "generated mult_map.v missing overlay marker "
                "(overlay template was not used)")
        if OVERLAY_MARKER in add_text:
            return fail(
                "generated add_sub_map.v unexpectedly contains overlay marker")
        if "add_sub_map.v. generated by vtr_arch_rules" not in add_text:
            return fail(
                "generated add_sub_map.v does not look like the shared template")

    print("PASS: overlay mult_map used; add_sub_map fell back to shared tpldir")
    return 0


if __name__ == "__main__":
    sys.exit(main())
