SRC +=  src/base/io/io.c \
    src/base/io/ioJson.c \
    src/base/io/ioReadAiger.c \
    src/base/io/ioReadBaf.c \
    src/base/io/ioReadBblif.c \
    src/base/io/ioReadBench.c \
    src/base/io/ioReadBlif.c \
    src/base/io/ioReadBlifAig.c \
    src/base/io/ioReadBlifMv.c \
    src/base/io/ioReadDsd.c \
    src/base/io/ioReadEdif.c \
    src/base/io/ioReadEqn.c \
    src/base/io/ioReadPla.c \
    src/base/io/ioReadPlaMo.c \
    src/base/io/ioReadVerilog.c \
    src/base/io/ioUtil.c \
    src/base/io/ioWriteAiger.c \
    src/base/io/ioWriteBaf.c \
    src/base/io/ioWriteBblif.c \
    src/base/io/ioWriteBench.c \
    src/base/io/ioWriteBlif.c \
    src/base/io/ioWriteBlifMv.c \
    src/base/io/ioWriteBook.c \
    src/base/io/ioWriteCnf.c \
    src/base/io/ioWriteDot.c \
    src/base/io/ioWriteEqn.c \
    src/base/io/ioWriteGml.c \
    src/base/io/ioWriteList.c \
    src/base/io/ioWritePla.c \
    src/base/io/ioWriteVerilog.c \
    src/base/io/ioWriteSmv.c
