//
// Created by amin on 5/10/23.
//

#ifndef VTR_PRIMITIVE_CRITICAL_UNIFORM_MOVE_GENERATOR_H
#define VTR_PRIMITIVE_CRITICAL_UNIFORM_MOVE_GENERATOR_H

#endif //VTR_PRIMITIVE_CRITICAL_UNIFORM_MOVE_GENERATOR_H
