SRC +=	src/aig/aig/aigCheck.c \
	src/aig/aig/aigCanon.c \
	src/aig/aig/aigCuts.c \
	src/aig/aig/aigDfs.c \
	src/aig/aig/aigDup.c \
	src/aig/aig/aigFanout.c \
	src/aig/aig/aigFrames.c \
	src/aig/aig/aigInter.c \
	src/aig/aig/aigJust.c \
	src/aig/aig/aigMan.c \
	src/aig/aig/aigMem.c \
	src/aig/aig/aigMffc.c \
	src/aig/aig/aigObj.c \
	src/aig/aig/aigOper.c \
	src/aig/aig/aigOrder.c \
	src/aig/aig/aigPack.c \
	src/aig/aig/aigPart.c \
	src/aig/aig/aigPartReg.c \
	src/aig/aig/aigPartSat.c \
	src/aig/aig/aigRepr.c \
	src/aig/aig/aigRet.c \
	src/aig/aig/aigRetF.c \
	src/aig/aig/aigScl.c \
	src/aig/aig/aigShow.c \
	src/aig/aig/aigSplit.c \
	src/aig/aig/aigTable.c \
	src/aig/aig/aigTiming.c \
	src/aig/aig/aigTruth.c \
	src/aig/aig/aigTsim.c \
	src/aig/aig/aigUtil.c \
	src/aig/aig/aigWin.c