SRC +=    src/aig/gia/giaAig.c \
    src/aig/gia/giaAgi.c \
    src/aig/gia/giaAiger.c \
    src/aig/gia/giaAigerExt.c \
    src/aig/gia/giaBalAig.c \
    src/aig/gia/giaBalLut.c \
    src/aig/gia/giaBalMap.c \
    src/aig/gia/giaBidec.c \
    src/aig/gia/giaCCof.c \
    src/aig/gia/giaCex.c \
    src/aig/gia/giaClp.c \
    src/aig/gia/giaCof.c \
    src/aig/gia/giaCone.c \
    src/aig/gia/giaCSatOld.c \
    src/aig/gia/giaCSat.c \
    src/aig/gia/giaCSat2.c \
    src/aig/gia/giaCSat3.c \
    src/aig/gia/giaCSatP.c \
    src/aig/gia/giaCTas.c \
    src/aig/gia/giaCut.c \
    src/aig/gia/giaDecs.c \
    src/aig/gia/giaDeep.c \
    src/aig/gia/giaDfs.c \
    src/aig/gia/giaDup.c \
    src/aig/gia/giaEdge.c \
    src/aig/gia/giaEmbed.c \
    src/aig/gia/giaEnable.c \
    src/aig/gia/giaEquiv.c \
    src/aig/gia/giaEra.c \
    src/aig/gia/giaEra2.c \
    src/aig/gia/giaEsop.c \
    src/aig/gia/giaExist.c \
    src/aig/gia/giaFalse.c \
    src/aig/gia/giaFanout.c \
    src/aig/gia/giaForce.c \
    src/aig/gia/giaFrames.c \
    src/aig/gia/giaFront.c \
    src/aig/gia/giaFx.c \
    src/aig/gia/giaGen.c \
    src/aig/gia/giaGig.c \
    src/aig/gia/giaGlitch.c \
    src/aig/gia/giaHash.c \
    src/aig/gia/giaIf.c \
    src/aig/gia/giaIff.c \
    src/aig/gia/giaIiff.c \
    src/aig/gia/giaIso.c \
    src/aig/gia/giaIso2.c \
    src/aig/gia/giaIso3.c \
    src/aig/gia/giaJf.c \
    src/aig/gia/giaKf.c \
    src/aig/gia/giaLf.c \
    src/aig/gia/giaMf.c \
    src/aig/gia/giaMan.c \
    src/aig/gia/giaMem.c \
    src/aig/gia/giaMfs.c \
    src/aig/gia/giaMini.c \
    src/aig/gia/giaMinLut.c \
    src/aig/gia/giaMinLut2.c \
    src/aig/gia/giaMuxes.c \
    src/aig/gia/giaNf.c \
    src/aig/gia/giaOf.c \
    src/aig/gia/giaPack.c \
    src/aig/gia/giaPat.c \
    src/aig/gia/giaPat2.c \
    src/aig/gia/giaPf.c \
    src/aig/gia/giaQbf.c \
    src/aig/gia/giaReshape1.c \
    src/aig/gia/giaReshape2.c \
    src/aig/gia/giaResub.c \
    src/aig/gia/giaResub2.c \
    src/aig/gia/giaResub3.c \
    src/aig/gia/giaResub6.c \
    src/aig/gia/giaRetime.c \
    src/aig/gia/giaRex.c \
    src/aig/gia/giaSatEdge.c \
    src/aig/gia/giaSatLE.c \
    src/aig/gia/giaSatLut.c \
    src/aig/gia/giaSatMap.c \
    src/aig/gia/giaSatoko.c \
    src/aig/gia/giaSatSyn.c \
    src/aig/gia/giaSat3.c \
    src/aig/gia/giaScl.c \
    src/aig/gia/giaScript.c \
    src/aig/gia/giaShow.c \
    src/aig/gia/giaShrink.c \
    src/aig/gia/giaShrink6.c \
    src/aig/gia/giaShrink7.c \
    src/aig/gia/giaSif.c \
    src/aig/gia/giaSim.c \
    src/aig/gia/giaSim2.c \
    src/aig/gia/giaSimBase.c \
    src/aig/gia/giaSort.c \
    src/aig/gia/giaSpeedup.c \
    src/aig/gia/giaSplit.c \
    src/aig/gia/giaStg.c \
    src/aig/gia/giaStoch.c \
    src/aig/gia/giaStr.c \
    src/aig/gia/giaSupMin.c \
    src/aig/gia/giaSupp.c \
    src/aig/gia/giaSupps.c \
    src/aig/gia/giaSweep.c \
    src/aig/gia/giaSweeper.c \
    src/aig/gia/giaSwitch.c \
    src/aig/gia/giaTim.c \
    src/aig/gia/giaTis.c \
    src/aig/gia/giaTransduction.cpp \
    src/aig/gia/giaTranStoch.c \
    src/aig/gia/giaTruth.c \
    src/aig/gia/giaTsim.c \
    src/aig/gia/giaTtopt.cpp \
    src/aig/gia/giaUnate.c \
    src/aig/gia/giaUtil.c
