SRC +=    src/sat/bmc/bmcBCore.c \
    src/sat/bmc/bmcBmc.c \
    src/sat/bmc/bmcBmc2.c \
    src/sat/bmc/bmcBmc3.c \
    src/sat/bmc/bmcBmcAnd.c \
    src/sat/bmc/bmcBmci.c \
    src/sat/bmc/bmcBmcG.c \
    src/sat/bmc/bmcBmcS.c \
    src/sat/bmc/bmcCexCare.c \
    src/sat/bmc/bmcCexCut.c \
    src/sat/bmc/bmcCexDepth.c \
    src/sat/bmc/bmcCexMin1.c \
    src/sat/bmc/bmcCexMin2.c \
    src/sat/bmc/bmcCexTools.c \
    src/sat/bmc/bmcChain.c \
    src/sat/bmc/bmcClp.c \
    src/sat/bmc/bmcEco.c \
    src/sat/bmc/bmcExpand.c \
    src/sat/bmc/bmcFault.c \
    src/sat/bmc/bmcFx.c \
    src/sat/bmc/bmcGen.c \
    src/sat/bmc/bmcICheck.c \
    src/sat/bmc/bmcInse.c \
    src/sat/bmc/bmcLoad.c \
    src/sat/bmc/bmcMaj.c \
    src/sat/bmc/bmcMaj2.c \
    src/sat/bmc/bmcMaj3.c \
    src/sat/bmc/bmcMaxi.c \
    src/sat/bmc/bmcMesh.c \
    src/sat/bmc/bmcMesh2.c \
    src/sat/bmc/bmcMulti.c \
    src/sat/bmc/bmcUnroll.c
