void check_rr_graph(IN t_graph_type graph_type,
		    IN int num_types,
		    IN t_type_ptr types,
		    IN int nx,
		    IN int ny,
		    IN struct s_grid_tile **grid,
		    IN int nodes_per_chan,
		    IN int Fs,
		    IN int num_seg_types,
			IN int num_switches,
		    IN t_segment_inf * segment_inf,
		    IN int global_route_switch,
		    IN int delayless_switch,
		    IN int wire_to_ipin_switch,
		    t_seg_details * seg_details,
		    int *Fc_in,
		    int *Fc_out,
		    t_ivec *** rr_node_indices,
		    int *****opin_to_track_map,
		    int *****ipin_to_track_map,
		    t_ivec **** track_to_ipin_lookup,
		    t_ivec *** switch_block_conn,
		    boolean * perturb_ipins);

void check_node(int inode,
		enum e_route_type route_type);
