/* This file just tests all the header files against each other for         *
 * consistency.  Make sure all your header files are included.  It should   *
 * be compiled with redudant declarations warnings on to look for           *
 * conflicting definitions of global variables.                             */

#include "util.h"
#include "vpr_types.h"
#include "globals.h"
#include "check_route.h"
#include "draw.h"
#include "graphics.h"
#include "hash.h"
#include "heapsort.h"
#include "place.h"
#include "place_and_route.h"
#include "read_netlist.h"
#include "print_netlist.h"
#include "check_netlist.h"
#include "read_place.h"
#include "mst.h"
#include "route_export.h"
#include "route_common.h"
#include "route_breadth_first.h"
#include "route_tree_timing.h"
#include "route_timing.h"
#include "rr_graph.h"
#include "rr_graph_util.h"
#include "rr_graph2.h"
#include "rr_graph_sbox.h"
#include "rr_graph_timing_params.h"
#include "rr_graph_indexed_data.h"
#include "rr_graph_area.h"
#include "check_rr_graph.h"
#include "stats.h"
#include "segment_stats.h"
#include "net_delay.h"
#include "path_delay.h"
#include "path_delay2.h"
#include "vpr_utils.h"
#include "timing_place_lookup.h"
#include "timing_place.h"
#include "ReadOptions.h"
#include "ReadArch.h"
#include "OptionTokens.h"
#include "ArchTokens.h"
#include "SetupVPR.h"
